# Generated by Django 6.0 on 2025-12-11 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_user_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workspace_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='workspace_templates/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='accounts.org')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number')], max_length=20)),
                ('source_header', models.CharField(blank=True, max_length=255, null=True)),
                ('x', models.IntegerField(default=10)),
                ('y', models.IntegerField(default=10)),
                ('width', models.IntegerField(default=160)),
                ('height', models.IntegerField(default=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('workspace', 'key')},
            },
        ),
    ]
