# Generated by Django 6.0 on 2025-12-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_orgrolechangelog_workspacemembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacefield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code')], max_length=20),
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dpi', models.PositiveIntegerField(default=300)),
                ('category', models.CharField(choices=[('APPAREL', 'Apparel'), ('FOOTWEAR', 'Footwear'), ('CANDLES', 'Candles'), ('IDOLS', 'Idols'), ('HOME_DECOR', 'Home Decor'), ('HOME_FURNISHING', 'Home Furnishing'), ('FMCG', 'FMCG'), ('ELECTRONICS', 'Electronics'), ('JEWELLERY', 'Jewellery'), ('BEAUTY', 'Beauty & Cosmetics'), ('EQUIPMENTS', 'Equipments'), ('SUPPLIES', 'Supplies'), ('OTHERS', 'Others')], default='OTHERS', max_length=30)),
                ('custom_category', models.CharField(blank=True, max_length=50)),
                ('is_base', models.BooleanField(default=False)),
                ('template_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_label_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-is_base', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabelTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code')], default='TEXT', max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=24)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workspaces.labeltemplate')),
                ('workspace_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_fields', to='workspaces.workspacefield')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
