# Generated by Django 6.0 on 2025-12-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspacefield_field_type_labeltemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('width_cm', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('dpi', models.PositiveIntegerField(default=300)),
                ('category', models.CharField(choices=[('APPAREL', 'Apparel'), ('FOOTWEAR', 'Footwear'), ('CANDLES', 'Candles'), ('IDOLS', 'Idols'), ('HOME_DECOR', 'Home Decor'), ('HOME_FURNISHING', 'Home Furnishing'), ('FMCG', 'FMCG'), ('ELECTRONICS', 'Electronics'), ('JEWELLERY', 'Jewellery'), ('BEAUTY', 'Beauty & Cosmetics'), ('EQUIPMENTS', 'Equipments'), ('SUPPLIES', 'Supplies'), ('OTHERS', 'Others')], default='other', max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL'), ('PRICE', 'Price'), ('SERIAL', 'Serial Number'), ('BARCODE', 'Barcode'), ('QRCODE', 'QR Code')], max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=140)),
                ('height', models.IntegerField(default=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workspaces.globaltemplate')),
            ],
        ),
    ]
