# Generated by Django 6.0 on 2025-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='org_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
