# Generated by Django 6.0 on 2025-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_org_org_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
